version: '3.8'

services:
  db:
    image: postgres
    container_name: quemistry-db
    environment:
      POSTGRES_DB: quemistry
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  question:
    build:
      context: ../question_ms
      dockerfile: Dockerfile
    container_name: question-ms
    depends_on:
      - db
    environment:
      - DB_NAME=quemistry
      - DB_URL=jdbc:postgresql://db:5432/quemistry
      - DB_USER=root
      - DB_PASSWORD=123456
    # ports:
    #   - "81:80"

  quiz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-ms
    depends_on:
      - db
      - question
    environment:
      - DB_NAME=quemistry
      - DB_URL=jdbc:postgresql://db:5432/quemistry
      - DB_USER=root
      - DB_PASSWORD=123456
      - QUESTION_SERVICE_URL=http://question:80
    ports:
      - "80:80"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      SWAGGER_JSON: /swagger/quiz_ms-health-openapi.yaml
      URLS: '[{"url":"./quiz_ms-health-openapi.yaml","name":"Health API"},
        {"url":"./quiz_ms-quiz-openapi.yaml","name":"Quiz API"},
        {"url":"./quiz_ms-test-openapi.yaml","name":"Test API"}]'
      QUIZ_MS_HOST: localhost
    volumes:
      - ./api:/swagger
    ports:
      - "8081:8080"

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

# volumes:
#  postgres_data:
