services:
  db:
    image: postgres
    container_name: quemistry-db
    environment:
      POSTGRES_DB: quemistry
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  question:
    build:
      context: ..\question_ms
      dockerfile: Dockerfile
    container_name: question-ms
    depends_on:
      - db
    environment:
      - DB_NAME=quemistry
      - DB_URL=jdbc:postgresql://db:5432/quemistry
      - DB_USER=root
      - DB_PASSWORD=123456

  quiz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-ms
    depends_on:
      - db
      - question
    environment:
      - DB_NAME=quemistry
      - DB_URL=jdbc:postgresql://db:5432/quemistry
      - DB_USER=root
      - DB_PASSWORD=123456
      - QUESTION_SERVICE_URL=http://question:80
    ports:
      - "80:80"

volumes:
  postgres_data:

