spring:
  application:
    name: quiz_ms
  cache:
    type: caffeine

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    schemas: qms_quiz
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa.:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 80

service:
  question:
    url: ${QUESTION_SERVICE_URL}

logging:
  level:
    javax.net.ssl: DEBUG