openapi: "3.1.0"
info:
  title: "quiz_ms health API"
  description: "quiz health API"
  version: "1.0.0"
servers:
  - url: "http://localhost"
paths:
  /v1/health:
    get:
      summary: "GET v1/health"
      operationId: "health"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
